In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/veri setleri/heart_disease_uci.csv')

In [ ]:
df.describe()

,id,age,trestbps,chol,thalch,oldpeak,ca,num
count,920.000000,920.000000,861.000000,890.000000,865.000000,858.000000,309.000000,920.000000
mean,460.500000,53.510870,132.132404,199.130337,137.545665,0.878788,0.676375,0.995652
std,265.725422,9.424685,19.066070,110.780810,25.926276,1.091226,0.935653,1.142693
min,1.000000,28.000000,0.000000,0.000000,60.000000,-2.600000,0.000000,0.000000
25%,230.750000,47.000000,120.000000,175.000000,120.000000,0.000000,0.000000,0.000000
50%,460.500000,54.000000,130.000000,223.000000,140.000000,0.500000,0.000000,1.000000
75%,690.250000,60.000000,140.000000,268.000000,157.000000,1.500000,1.000000,2.000000
max,920.000000,77.000000,200.000000,603.000000,202.000000,6.200000,3.000000,4.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       920 non-null    int64
 2   sex       920 non-null    object
 3   dataset   920 non-null    object
 4   cp        920 non-null    object
 5   trestbps  861 non-null    float64
 6   chol      890 non-null    float64
 7   fbs       830 non-null    object
 8   restecg   918 non-null    object
 9   thalch    865 non-null    float64
 10  exang     865 non-null    object
 11  oldpeak   858 non-null    float64
 12  slope     611 non-null    object
 13  ca        309 non-null    float64
 14  thal      434 non-null    object
 15  num       920 non-null    int64
dtypes: float64(5), int64(3), object(8)
memory usage: 115.1+ KB

In [ ]:
df.isnull().sum()

id            0
age           0
sex           0
dataset       0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
num           0
dtype: int64

In [ ]:
categorical_columns = df.select_dtypes(include=['object', 'category']).columns

In [ ]:
numeric_columns = df.select_dtypes(include=['number']).columns

In [ ]:

print("Kategorik Sütunlar:", categorical_columns)
print("Sayısal Sütunlar:", numeric_columns)

Kategorik Sütunlar: Index(['sex', 'dataset', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'thal'], dtype='object')
Sayısal Sütunlar: Index(['id', 'age', 'trestbps', 'chol', 'thalch', 'oldpeak', 'ca', 'num'], dtype='object')

In [ ]:
for column in categorical_columns:
    if df[column].isnull().sum() > 0:
        df[column].fillna(df[column].mode()[0], inplace=True)
print("oldu!!!")

oldu!!!

<ipython-input-120-bb89617587ac>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].mode()[0], inplace=True)
<ipython-input-120-bb89617587ac>:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[column].fillna(df[column].mode()[0], inplace=True)

In [ ]:
for column in numeric_columns:
    if df[column].isnull().sum() > 0:
        df[column].fillna(df[column].median(), inplace=True)
print("oldu!!!")

oldu!!!

<ipython-input-121-1a44fbb923f1>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].median(), inplace=True)

In [ ]:
print(df[numeric_columns].isnull().sum())

id          0
age         0
trestbps    0
chol        0
thalch      0
oldpeak     0
ca          0
num         0
dtype: int64

In [ ]:
print(df[categorical_columns].isnull().sum())

sex        0
dataset    0
cp         0
fbs        0
restecg    0
exang      0
slope      0
thal       0
dtype: int64

In [ ]:
# Her bir kategorik sütunun benzersiz değerlerini listeleme
unique_values = {col: df[col].unique() for col in categorical_columns}

# Sonuçları yazdırma
for col, values in unique_values.items():
    print(f"Sütun: {col}")
    print(f"Benzersiz Değerler: {values}")
    print("-" * 50)

Sütun: sex
Benzersiz Değerler: ['Male' 'Female']
--------------------------------------------------
Sütun: dataset
Benzersiz Değerler: ['Cleveland' 'Hungary' 'Switzerland' 'VA Long Beach']
--------------------------------------------------
Sütun: cp
Benzersiz Değerler: ['typical angina' 'asymptomatic' 'non-anginal' 'atypical angina']
--------------------------------------------------
Sütun: fbs
Benzersiz Değerler: [ True False]
--------------------------------------------------
Sütun: restecg
Benzersiz Değerler: ['lv hypertrophy' 'normal' 'st-t abnormality']
--------------------------------------------------
Sütun: exang
Benzersiz Değerler: [False  True]
--------------------------------------------------
Sütun: slope
Benzersiz Değerler: ['downsloping' 'flat' 'upsloping']
--------------------------------------------------
Sütun: thal
Benzersiz Değerler: ['fixed defect' 'normal' 'reversable defect']
--------------------------------------------------

ENCODİNG

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Label Encoding
label_encoder = LabelEncoder()
df['sex'] = label_encoder.fit_transform(df['sex'])  # Male → 0, Female → 1
df['fbs'] = label_encoder.fit_transform(df['fbs'])
df['exang'] = label_encoder.fit_transform(df['exang'])

# OneHotEncoding
one_hot_encoded = pd.get_dummies(df[['dataset', 'cp', 'restecg', 'slope','thal']], drop_first=True)
df = pd.concat([df, one_hot_encoded], axis=1)
df.drop(['dataset', 'cp', 'restecg','slope','thal'], axis=1, inplace=True)

STANDARTLAŞTIRMA

In [ ]:
print(numeric_columns)

Index(['id', 'age', 'trestbps', 'chol', 'thalch', 'oldpeak', 'ca', 'num'], dtype='object')

In [ ]:
from sklearn.preprocessing import StandardScaler

target_column = 'num'
numeric_columns = numeric_columns.drop(target_column)
scaler = StandardScaler()
df[numeric_columns] = scaler.fit_transform(df[numeric_columns])

In [ ]:
print(df[numeric_columns].describe())

               id           age    trestbps          chol        thalch  \
count  920.000000  9.200000e+02  920.000000  9.200000e+02  9.200000e+02
mean     0.000000  6.178632e-17    0.000000 -9.267949e-17 -4.016111e-16
std      1.000544  1.000544e+00    1.000544  1.000544e+00  1.000544e+00
min     -1.730169 -2.708286e+00   -7.157623 -1.834346e+00 -3.091427e+00
25%     -0.865085 -6.912073e-01   -0.650479 -2.033264e-01 -7.039908e-01
50%      0.000000  5.192709e-02   -0.108217  2.118840e-01  9.182113e-02
75%      0.865085  6.888994e-01    0.434045  6.156245e-01  7.284707e-01
max      1.730169  2.493654e+00    3.687618  3.698734e+00  2.558838e+00

            oldpeak            ca
count  9.200000e+02  9.200000e+02
mean  -2.316987e-17  6.178632e-17
std    1.000544e+00  1.000544e+00
min   -3.265577e+00 -3.613997e-01
25%   -8.068863e-01 -3.613997e-01
50%   -3.340612e-01 -3.613997e-01
75%    6.115890e-01 -3.613997e-01
max    5.056145e+00  4.411152e+00

In [ ]:
df.to_csv("heart_disease_sonn.csv", index=False)
print("Dosya kaydedildi")

Dosya kaydedildi kanka 🚀